language: ruby
rvm:
  - "2.2.6"

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - bundle exec rake db:migrate
  - bundle exec rails s -d
bundler_args: --binstubs=./bundler_stubs
